#!/usr/bin/env python3
"""
T2 Factor Timing Complete Pipeline Runner

INPUT FILES:
- GDELT.xlsx (required: defines the single monthly analysis window for the full run)
- AssetList.xlsx (required, for Step 0)
- Raw Bloomberg data files (for Step 1)
- Step Factor Categories.xlsx (for Step 5 and other steps)

OUTPUT FILES:
- All intermediate and final outputs generated by the pipeline
- pipeline_execution.log (detailed execution log)
- pipeline_summary.txt (execution summary)

PURPOSE:
This script runs the complete T2 Factor Timing pipeline in the correct sequence,
with error handling, progress tracking, and comprehensive logging.

VERSION: 1.1
LAST UPDATED: 2026-03-31
"""

import os
import sys
import subprocess
import datetime
import logging
import time
from pathlib import Path
import traceback

class PipelineRunner:
    def __init__(self, base_dir=None):
        """Initialize the pipeline runner."""
        self.base_dir = Path(base_dir) if base_dir else Path(__file__).parent
        self.log_file = self.base_dir / "pipeline_execution.log"
        self.summary_file = self.base_dir / "pipeline_summary.txt"
        
        # Setup logging
        logging.basicConfig(
            level=logging.INFO,
            format='%(asctime)s - %(levelname)s - %(message)s',
            handlers=[
                logging.FileHandler(self.log_file),
                logging.StreamHandler(sys.stdout)
            ]
        )
        self.logger = logging.getLogger(__name__)
        
        # Define pipeline steps in order
        self.pipeline_steps = [
            {
                "name": "Step 0 - Create P2P Scores",
                "script": "Step Zero Create P2P Scores.py",
                "required": True,
                "description": "Build Price-to-Peak momentum scores for country ETFs"
            },
            {
                "name": "Step 1 - Create T2 Master",
                "script": "Step One Create T2Master.py",
                "required": True,
                "description": "Ingest raw Bloomberg data and create master dataset"
            },
            {
                "name": "Step 2 - Create Normalized Tidy",
                "script": "Step Two Create Normalized Tidy.py",
                "required": True,
                "description": "Normalize variables cross-sectionally and in time-series"
            },
            {
                "name": "Step 2.5 - Create Benchmark Returns",
                "script": "Step Two Point Five Create Benchmark Rets.py",
                "required": True,
                "description": "Build equal-weight and market-cap benchmarks"
            },
            {
                "name": "Step 3 - Top 20 Portfolios",
                "script": "Step Three Top20 Portfolios Fast.py",
                "required": True,
                "description": "Create Top 20% factor portfolios and analyze performance"
            },
            {
                "name": "Step 4 - Create Monthly Top20 Returns",
                "script": "Step Four Create Monthly Top20 Returns FAST.py",
                "required": True,
                "description": "Create fuzzy soft-band portfolios and T60 calculations"
            },
            {
                "name": "Step 5 - FAST Optimizer",
                "script": "Step Five FAST.py",
                "required": True,
                "description": "Optimize multi-factor allocations using CVXPY"
            },
            {
                "name": "Step 6 - Create Country Alphas",
                "script": "Step Six Create Country alphas from Factor alphas.py",
                "required": True,
                "description": "Convert factor alphas to country alphas"
            },
            {
                "name": "Step 7 - Visualize Factor Weights",
                "script": "Step Seven Visualize Factor Weights.py",
                "required": True,
                "description": "Create visualizations of factor weights"
            },
            {
                "name": "Step 8 - Write Country Weights",
                "script": "Step Eight Write Country Weights.py",
                "required": True,
                "description": "Convert factor weights to country weights"
            },
            {
                "name": "Step 9 - Calculate Portfolio Returns",
                "script": "Step Nine Calculate Portfolio Returns.py",
                "required": True,
                "description": "Calculate final portfolio returns and performance"
            },
                        {
                "name": "Step 14 - Target Optimization",
                "script": "Step Fourteen Target Optimization.py",
                "required": True,
                "description": "Country-level optimization with turnover control"
            },
            {
                "name": "Step 16 - Factor Market Condition Analysis",
                "script": "Step Sixteen Market Regime Analysis.py",
                "required": True,
                "description": "Factor performance under market conditions",
                "continue_on_failure": True
            },
            {
                "name": "Step 17 - GMM Regime Analysis",
                "script": "Step Seventeen Market Regime Analysis.py",
                "required": True,
                "description": "Data-driven regime analysis using GMM",
                "continue_on_failure": True
            },
            {
                "name": "Step 18 - Asset Class Charts",
                "script": "Step Eighteen Asset Class Charts.py",
                "required": True,
                "description": "Create asset class and country weight visualizations",
                "continue_on_failure": True
            },
            {
                "name": "Step 20 - PORCH Factor Exposure",
                "script": "Step Twenty PORCH.py",
                "required": True,
                "description": "Compare factor exposures across strategies",
                "continue_on_failure": True
            },
            {
                "name": "Step 21 - Master Report",
                "script": "Step Twenty One Master Report.py",
                "required": True,
                "description": "Merge all PDF outputs into a single master report",
                "continue_on_failure": True
            },
            {
                "name": "FINALFINAL - Latest Alphas and Weights",
                "script": "Step FINALFINAL.py",
                "required": True,
                "description": "Create final snapshot of alphas and weights"
            }
        ]
        
        self.execution_results = []
        
    def check_prerequisites(self):
        """Check if required input files exist."""
        self.logger.info("Checking prerequisites...")
        
        # Check for essential files
        essential_files = [
            "Step Factor Categories.xlsx",
            "GDELT.xlsx",  # defines analysis date range (T2_GDELT_analysis_window.py)
        ]
        
        missing_files = []
        for file in essential_files:
            file_path = self.base_dir / file
            if not file_path.exists():
                missing_files.append(file)
        
        if missing_files:
            self.logger.warning(f"Missing essential files: {missing_files}")
            self.logger.warning("Some steps may fail without these files")
        
        # Check for optional files
        optional_files = [
            "AssetList.xlsx"
        ]
        
        for file in optional_files:
            file_path = self.base_dir / file
            if not file_path.exists():
                self.logger.info(f"Optional file not found: {file} (Step 0 will be skipped)")
        
        return True
    
    def run_script(self, script_name, step_info):
        """Run a single Python script and return execution result."""
        script_path = self.base_dir / script_name
        
        if not script_path.exists():
            error_msg = f"Script not found: {script_name}"
            self.logger.error(error_msg)
            return {
                "step": step_info["name"],
                "script": script_name,
                "status": "FAILED",
                "error": error_msg,
                "duration": 0,
                "timestamp": datetime.datetime.now()
            }
        
        self.logger.info(f"Running: {step_info['name']}")
        self.logger.info(f"Script: {script_name}")
        self.logger.info(f"Description: {step_info['description']}")
        
        start_time = time.time()
        
        try:
            # Run the script
            result = subprocess.run(
                [sys.executable, str(script_path)],
                cwd=str(self.base_dir),
                capture_output=True,
                text=True,
                timeout=3600  # 1 hour timeout per step
            )
            
            duration = time.time() - start_time
            
            if result.returncode == 0:
                self.logger.info(f"✓ {step_info['name']} completed successfully in {duration:.2f} seconds")
                if result.stdout:
                    self.logger.info(f"Output: {result.stdout[:500]}...")
                
                return {
                    "step": step_info["name"],
                    "script": script_name,
                    "status": "SUCCESS",
                    "error": None,
                    "duration": duration,
                    "timestamp": datetime.datetime.now(),
                    "stdout": result.stdout
                }
            else:
                error_msg = f"Script failed with return code {result.returncode}"
                self.logger.error(f"✗ {step_info['name']} failed: {error_msg}")
                self.logger.error(f"Error output: {result.stderr}")
                
                return {
                    "step": step_info["name"],
                    "script": script_name,
                    "status": "FAILED",
                    "error": error_msg,
                    "duration": duration,
                    "timestamp": datetime.datetime.now(),
                    "stderr": result.stderr
                }
                
        except subprocess.TimeoutExpired:
            error_msg = f"Script timed out after 1 hour"
            self.logger.error(f"✗ {step_info['name']} {error_msg}")
            
            return {
                "step": step_info["name"],
                "script": script_name,
                "status": "TIMEOUT",
                "error": error_msg,
                "duration": 3600,
                "timestamp": datetime.datetime.now()
            }
            
        except Exception as e:
            error_msg = f"Unexpected error: {str(e)}"
            self.logger.error(f"✗ {step_info['name']} {error_msg}")
            self.logger.error(traceback.format_exc())
            
            return {
                "step": step_info["name"],
                "script": script_name,
                "status": "ERROR",
                "error": error_msg,
                "duration": time.time() - start_time,
                "timestamp": datetime.datetime.now()
            }
    
    def run_pipeline(self, skip_optional=True):
        """Run the complete pipeline."""
        self.logger.info("=" * 80)
        self.logger.info("T2 Factor Timing Complete Pipeline Execution")
        self.logger.info("=" * 80)
        self.logger.info(f"Started at: {datetime.datetime.now()}")
        self.logger.info(f"Base directory: {self.base_dir}")
        self.logger.info(f"Total steps: {len(self.pipeline_steps)}")
        self.logger.info("=" * 80)

        # Single analysis period for the whole run (from GDELT.xlsx)
        gdelt_path = self.base_dir / "GDELT.xlsx"
        try:
            if str(self.base_dir) not in sys.path:
                sys.path.insert(0, str(self.base_dir))
            from T2_GDELT_analysis_window import get_gdelt_analysis_window

            _s, _e = get_gdelt_analysis_window(gdelt_path=str(gdelt_path))
            self.logger.info(
                "Pipeline analysis window (GDELT-aligned): %s to %s",
                _s.strftime("%Y-%m-%d"),
                _e.strftime("%Y-%m-%d"),
            )
        except Exception as ex:
            self.logger.warning(
                "Could not load GDELT analysis window from %s: %s",
                gdelt_path,
                ex,
            )
        
        # Check prerequisites
        if not self.check_prerequisites():
            self.logger.error("Prerequisite check failed. Aborting pipeline.")
            return False
        
        pipeline_start_time = time.time()
        successful_steps = 0
        failed_steps = 0
        
        for i, step in enumerate(self.pipeline_steps, 1):
            # Skip optional steps if requested
            if skip_optional and not step["required"]:
                self.logger.info(f"Skipping optional step: {step['name']}")
                continue
            
            self.logger.info(f"\n--- Step {i}/{len(self.pipeline_steps)} ---")
            
            # Run the step
            result = self.run_script(step["script"], step)
            self.execution_results.append(result)
            
            if result["status"] == "SUCCESS":
                successful_steps += 1
            else:
                failed_steps += 1

                # Stop if a required step fails unless the step is marked to continue on failure
                if step.get("continue_on_failure"):
                    self.logger.warning(f"Step failed but flagged to continue: {step['name']}")
                elif step["required"]:
                    self.logger.error(f"Required step failed. Stopping pipeline.")
                    break
                else:
                    self.logger.warning(f"Optional step failed. Continuing pipeline.")
        
        pipeline_duration = time.time() - pipeline_start_time
        
        # Generate summary
        self.generate_summary(pipeline_duration, successful_steps, failed_steps)
        
        self.logger.info("=" * 80)
        self.logger.info("Pipeline execution completed")
        self.logger.info(f"Total duration: {pipeline_duration:.2f} seconds ({pipeline_duration/60:.1f} minutes)")
        self.logger.info(f"Successful steps: {successful_steps}")
        self.logger.info(f"Failed steps: {failed_steps}")
        self.logger.info(f"Log file: {self.log_file}")
        self.logger.info(f"Summary file: {self.summary_file}")
        self.logger.info("=" * 80)
        
        return failed_steps == 0
    
    def generate_summary(self, total_duration, successful_steps, failed_steps):
        """Generate execution summary."""
        summary_lines = [
            "T2 Factor Timing Pipeline Execution Summary",
            "=" * 50,
            f"Started: {self.execution_results[0]['timestamp'] if self.execution_results else 'N/A'}",
            f"Completed: {datetime.datetime.now()}",
            f"Total Duration: {total_duration:.2f} seconds ({total_duration/60:.1f} minutes)",
            f"Total Steps: {len(self.pipeline_steps)}",
            f"Successful: {successful_steps}",
            f"Failed: {failed_steps}",
            "",
            "Step-by-Step Results:",
            "-" * 50
        ]
        
        for result in self.execution_results:
            status_symbol = "✓" if result["status"] == "SUCCESS" else "✗"
            summary_lines.append(
                f"{status_symbol} {result['step']} - {result['status']} "
                f"({result['duration']:.2f}s)"
            )
            if result["error"]:
                summary_lines.append(f"    Error: {result['error']}")
        
        summary_lines.extend([
            "",
            "Generated Files:",
            "-" * 50,
            "Check the working directory for all output files generated by the pipeline.",
            "Key outputs include:",
            "- T2_Master.xlsx",
            "- Normalized_T2_Master.xlsx",
            "- T2_Optimizer.xlsx",
            "- T60.xlsx",
            "- T2_rolling_window_weights.xlsx",
            "- T2_Final_Country_Weights.xlsx",
            "- T2_Optimized_Country_Weights.xlsx",
            "- Various PDF reports and Excel analyses",
            "",
            f"Detailed log: {self.log_file}"
        ])
        
        # Write summary to file
        with open(self.summary_file, 'w') as f:
            f.write('\n'.join(summary_lines))
        
        # Also print to console
        self.logger.info("\n" + '\n'.join(summary_lines))

def main():
    """Main execution function."""
    import argparse
    
    parser = argparse.ArgumentParser(description="Run T2 Factor Timing Complete Pipeline")
    parser.add_argument(
        "--base-dir",
        help="Base directory containing the scripts (default: current directory)",
        default=None
    )
    parser.add_argument(
        "--include-optional",
        action="store_true",
        help="Include optional steps (default: skip optional steps)"
    )
    parser.add_argument(
        "--step",
        help="Run only a specific step (e.g., 'Step 5' or '5')",
        default=None
    )
    
    args = parser.parse_args()
    
    # Create pipeline runner
    runner = PipelineRunner(base_dir=args.base_dir)
    
    if args.step:
        # Run single step
        try:
            step_num = int(args.step)
            if 1 <= step_num <= len(runner.pipeline_steps):
                step = runner.pipeline_steps[step_num - 1]
                runner.logger.info(f"Running single step: {step['name']}")
                result = runner.run_script(step["script"], step)
                runner.execution_results.append(result)
                runner.generate_summary(0, 1 if result["status"] == "SUCCESS" else 0, 
                                      0 if result["status"] == "SUCCESS" else 1)
            else:
                runner.logger.error(f"Invalid step number: {step_num}")
                return 1
        except ValueError:
            # Search by name
            for step in runner.pipeline_steps:
                if args.step.lower() in step["name"].lower():
                    runner.logger.info(f"Running single step: {step['name']}")
                    result = runner.run_script(step["script"], step)
                    runner.execution_results.append(result)
                    runner.generate_summary(0, 1 if result["status"] == "SUCCESS" else 0, 
                                          0 if result["status"] == "SUCCESS" else 1)
                    break
            else:
                runner.logger.error(f"Step not found: {args.step}")
                return 1
    else:
        # Run complete pipeline
        success = runner.run_pipeline(skip_optional=not args.include_optional)
        return 0 if success else 1

if __name__ == "__main__":
    sys.exit(main())
